[package]
name = "link-daemon"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "linkd"
path = "src/main.rs"
required-features = ["daemon", "gstreamer"]

[features]
default = ["daemon", "gstreamer", "pipewire"]
daemon = ["dep:link-ipc"]
gstreamer = ["dep:link-media", "link-media/gstreamer"]
pipewire = ["dep:link-audio", "link-audio/pipewire"]
network = ["dep:link-ipc", "dep:link-media", "link-ipc/network", "link-media/network"]

[dependencies]
clap.workspace = true
ctrlc.workspace = true
humantime.workspace = true
link-audio = { workspace = true, optional = true }
link-core.workspace = true
link-ipc = { workspace = true, optional = true }
link-media = { workspace = true, optional = true }
link-linux = { path = "../link-linux", version = "=1.0.2" }
link-v4l2.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
