[package]
name = "link-core"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
humantime.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
